name: mazad
description: A new Flutter project.

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.0.15
  flutterflow_ui: 0.2.0+1
  image_picker: ^1.0.2
  flip_panel_plus: ^1.0.0+3
  carousel_slider: ^4.2.1
  aligned_dialog: ^0.0.7
  cached_memory_image: ^1.3.1
  flutter_clickpay_bridge: ^2.3.2


dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
